name: build-deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '28.1'
        elixir-version: '1.19'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: mix deps.get

    - name: Run script
      run: bash bin/build-static

    - name: Publish Preview
      uses: cloudflare/wrangler-action@v3
      if: ${{ github.event_name == 'pull_request' }}
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy ./visualization/dist --project-name=api-reference
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Bump
      uses: bump-sh/github-action@v1
      if: ${{ github.event_name == 'push' }}
      with:
        doc: arta
        token: ${{ secrets.BUMP_SECRET_API_KEY }}
        file: openapi.json
